<?php

/*
Copyright 2024 Blnk Finance Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

declare(strict_types=1);

namespace Blnk\Cmd\CertMagic\Acme;

/**
 * Problem carries the details of an error from HTTP APIs as
 * defined in RFC 7807: https://tools.ietf.org/html/rfc7807
 * and as extended by RFC 8555 §6.7:
 * https://tools.ietf.org/html/rfc8555#section-6.7
 *
 * (acmez acme/problem.go; it is an exception so it can be thrown and found
 * again in a wrapped error chain with {@see from()} — Go's `errors.As`.)
 */
class Problem extends \RuntimeException
{
    /** The ACME error URN prefix. */
    public const ProblemTypeNamespace = 'urn:ietf:params:acme:error:';

    public const ProblemTypeAccountDoesNotExist = self::ProblemTypeNamespace . 'accountDoesNotExist';
    public const ProblemTypeAlreadyRevoked = self::ProblemTypeNamespace . 'alreadyRevoked';
    public const ProblemTypeBadCSR = self::ProblemTypeNamespace . 'badCSR';
    public const ProblemTypeBadNonce = self::ProblemTypeNamespace . 'badNonce';
    public const ProblemTypeBadPublicKey = self::ProblemTypeNamespace . 'badPublicKey';
    public const ProblemTypeBadRevocationReason = self::ProblemTypeNamespace . 'badRevocationReason';
    public const ProblemTypeBadSignatureAlgorithm = self::ProblemTypeNamespace . 'badSignatureAlgorithm';
    public const ProblemTypeCAA = self::ProblemTypeNamespace . 'caa';
    public const ProblemTypeCompound = self::ProblemTypeNamespace . 'compound';
    public const ProblemTypeConnection = self::ProblemTypeNamespace . 'connection';
    public const ProblemTypeDNS = self::ProblemTypeNamespace . 'dns';
    public const ProblemTypeExternalAccountRequired = self::ProblemTypeNamespace . 'externalAccountRequired';
    public const ProblemTypeIncorrectResponse = self::ProblemTypeNamespace . 'incorrectResponse';
    public const ProblemTypeInvalidContact = self::ProblemTypeNamespace . 'invalidContact';
    public const ProblemTypeMalformed = self::ProblemTypeNamespace . 'malformed';
    public const ProblemTypeOrderNotReady = self::ProblemTypeNamespace . 'orderNotReady';
    public const ProblemTypeRateLimited = self::ProblemTypeNamespace . 'rateLimited';
    public const ProblemTypeRejectedIdentifier = self::ProblemTypeNamespace . 'rejectedIdentifier';
    public const ProblemTypeServerInternal = self::ProblemTypeNamespace . 'serverInternal';
    public const ProblemTypeTLS = self::ProblemTypeNamespace . 'tls';
    public const ProblemTypeUnauthorized = self::ProblemTypeNamespace . 'unauthorized';
    public const ProblemTypeUnsupportedContact = self::ProblemTypeNamespace . 'unsupportedContact';
    public const ProblemTypeUnsupportedIdentifier = self::ProblemTypeNamespace . 'unsupportedIdentifier';
    public const ProblemTypeUserActionRequired = self::ProblemTypeNamespace . 'userActionRequired';

    /**
     * "type" (string) - A URI reference [RFC3986] that identifies the
     * problem type. When this member is not present, its value is assumed
     * to be "about:blank". §3.1
     */
    public string $type = '';

    /** "title" (string) - A short, human-readable summary of the problem type. §3.1 */
    public string $title = '';

    /** "status" (number) - The HTTP status code generated by the origin server for this occurrence of the problem. §3.1 */
    public int $status = 0;

    /**
     * "detail" (string) - A human-readable explanation specific to this
     * occurrence of the problem. §3.1
     *
     * RFC 8555 §6.7: "Clients SHOULD display the 'detail' field of all errors."
     */
    public string $detail = '';

    /** "instance" (string) - A URI reference that identifies the specific occurrence of the problem. §3.1 */
    public string $instance = '';

    /**
     * "Sometimes a CA may need to return multiple errors in response to a
     * request. [...] In this situation, an ACME problem document MAY contain the
     * 'subproblems' field, containing a JSON array of problem documents."
     * RFC 8555 §6.7.1
     *
     * @var Subproblem[]
     */
    public array $subproblems = [];

    /**
     * For convenience, we've added this field to associate with a value
     * that is related to or caused the problem. It is not part of the
     * spec, but, if a challenge fails for example, we can associate the
     * error with the problematic authz object by setting this field.
     * Challenge failures will have this set to an Authorization type.
     */
    public mixed $resource = null;

    /**
     * PHP port: the HTTP response the problem document came with (Go's
     * `httpReq` returns the response next to the error; PHP carries it on
     * the exception so retry decisions can look at the status code).
     */
    public ?\Psr\Http\Message\ResponseInterface $httpResponse = null;

    /**
     * @param Subproblem[] $subproblems
     */
    public function __construct(string $type = '', string $title = '', int $status = 0, string $detail = '', string $instance = '', array $subproblems = [])
    {
        $this->type = $type;
        $this->title = $title;
        $this->status = $status;
        $this->detail = $detail;
        $this->instance = $instance;
        $this->subproblems = $subproblems;
        parent::__construct($this->errorString(), $status);
    }

    /**
     * fromArray decodes a problem document.
     *
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        $subproblems = [];
        foreach ((array) ($data['subproblems'] ?? []) as $sub) {
            if (\is_array($sub)) {
                $subproblems[] = Subproblem::fromArray($sub);
            }
        }
        return new static(
            (string) ($data['type'] ?? ''),
            (string) ($data['title'] ?? ''),
            (int) ($data['status'] ?? 0),
            (string) ($data['detail'] ?? ''),
            (string) ($data['instance'] ?? ''),
            $subproblems
        );
    }

    /**
     * errorString is Go's `Problem.Error()`.
     */
    public function errorString(): string
    {
        // TODO: 7.3.3: Handle changes to Terms of Service (notice it uses the Instance field and Link header)

        // RFC 8555 §6.7: "Clients SHOULD display the 'detail' field of all errors."
        $s = sprintf('HTTP %d %s - %s', $this->status, $this->type, $this->detail);
        foreach ($this->subproblems as $v) {
            $s .= sprintf(', problem "%s": %s', $v->type, $v->detail);
            if ($v->identifier->type !== '' || $v->identifier->value !== '') {
                $s .= sprintf(' (%s_identifier=%s)', $v->identifier->type, $v->identifier->value);
            }
        }
        if ($this->instance !== '') {
            $s .= ', url: ' . $this->instance;
        }
        return $s;
    }

    /**
     * from finds a Problem in an error chain (Go: `errors.As(err, &problem)`).
     */
    public static function from(?\Throwable $err): ?Problem
    {
        while ($err !== null) {
            if ($err instanceof Problem) {
                return $err;
            }
            $err = $err->getPrevious();
        }
        return null;
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        $out = ['type' => $this->type];
        if ($this->title !== '') {
            $out['title'] = $this->title;
        }
        if ($this->status !== 0) {
            $out['status'] = $this->status;
        }
        if ($this->detail !== '') {
            $out['detail'] = $this->detail;
        }
        if ($this->instance !== '') {
            $out['instance'] = $this->instance;
        }
        if ($this->subproblems !== []) {
            $out['subproblems'] = array_map(static fn (Subproblem $s): array => $s->toArray(), $this->subproblems);
        }
        return $out;
    }
}
